---
title: "Week 2 Programming Quiz"
output: html_notebook
---

**Question 1**

Suppose I define the following function in R

```r
cube <- function(x, n) {
        x^3
}
```

What is the result of running

```r
cube(3)
```

in R after defining this function?

Ans:

```{r}
cube <- function(x, n) {
        x^3
}
cube(3)
```

**Question 3**

Consider the following function

```r
f <- function(x) {
        g <- function(y) {
                y + z
        }
        z <- 4
        x + g(x)
}
```

If I then run in R

```R
z <- 10
f(3)
```

What value is returned?

```{r}
f <- function(x) {
        g <- function(y) {
                y + z
        }
        z <- 4
        x + g(x)
}
z <- 10
f(3)
```

**Question 4**

Consider the following expression:

```r
x <- 5
y <- if(x < 3) {
        NA
} else {
        10
}
```

What is the value of 'y' after evaluating this expression?

```{r}
x <- 5
y <- if(x < 3) {
        NA
} else {
        10
}
y
```

